apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: services
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: ricsanfre/microservices-customer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: customer-config
      restartPolicy: Always
      