server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  # No sampling configuration
  tracing:
    sampling:
      probability: 1.0
  # export to a zipkin server

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


# Adding traceId and SpanId to logs
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
