apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: services
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: fraud
          image: ricsanfre/microservices-notification
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
      