server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: password
    url: jdbc:postgresql://db:5432/fraud
    username: ricsanfre
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false

management:
  # No sampling configuration
  tracing:
    sampling:
      probability: 1.0
  # export to a zipkin server
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# Adding traceId and SpanId to logs
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
