apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  namespace: services
  labels:
    app: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: ricsanfre/microservices-fraud
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: fraud-config
      restartPolicy: Always
      